#!/usr/bin/env sh

yabai -m config layout                      bsp

#padding & gap
yabai -m config top_padding                 30
yabai -m config bottom_padding              20
yabai -m config left_padding                32
yabai -m config right_padding               32
yabai -m config window_gap                  10

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# border 不能设置圆角 放弃
#yabai -m config window_border  off
#yabai -m config window_border_width         1
#yabai -m config active_window_border_color   0xffffb5b5


# ====== List of rules =========================

# yabai -m rule --add label=chrome app="^Google Chrome$" space=2

# 临时性的App, manage=off不受到yabai平铺式的限制
otherApp='^(IINA|访达|Calendar|日历|System Preferences|系统偏好设置|1Password 7|Mail|微信|WeChatc|QQ|uTools|网易云音乐|Panda|The Unarchiver|Tencent Lemon|归档实用工具)$'
yabai -m rule --add app="${otherApp}" manage=off


#安装配置好limelight后打开注释可使用
#killall limelight &> /dev/null
#limelight &> /dev/null &
